include $(APPDIR)/Make.defs

# LED driver test built-in application info

PROGNAME = $(CONFIG_CUSTOM_APP_PROGNAME)
PRIORITY = $(CONFIG_CUSTOM_APP_PRIORITY)
STACKSIZE = $(CONFIG_CUSTOM_APP_STACKSIZE)
MODULE = $(CONFIG_CUSTOM_APP)

# LED driver test

MAINSRC = custom_app_main.c

include $(APPDIR)/Application.mk
